name:                http2-client-exe
version:             0.2.0.0
github:              "lucasdicioccio/http2-client-exe"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018 Lucas DiCioccio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A command-line http2 client.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A reference command-line tool using http2-client. Please see the README on GitHub at <https://github.com/lucasdicioccio/http2-client-exe#readme>

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- data-default-class
- http2
- http2-client
- lifted-async
- lifted-base
- optparse-applicative
- time
- tls

executables:
  http2-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
